"use strict";
let book = 'English';
let car = "Mark X";
console.log("Is book == 'English'? I predict true.");
console.log(book == 'English', "\n");
console.log("Is book != 'english'? I predict true.");
console.log(book != 'english', "\n");
console.log("Is book == 'english'? I predict false.");
console.log(book == 'english', "\n");
console.log("Is book != 'English'? I predict false.");
console.log(book != 'English', "\n");
console.log("Is car == 'mark X'? I predict false.");
console.log(car == 'mark X', "\n");
console.log("Is car == 'Mark X'? I predict true.");
console.log(car == 'Mark X', "\n");
console.log("Is car == 'Mark x'? I predict false.");
console.log(car == 'Mark x', "\n");
console.log("Is car != 'Mark x'? I predict true.");
console.log(car != 'Mark x', "\n");
console.log("Is car != 'Mark X'? I predict false.");
console.log(car !== 'Mark X', "\n");
console.log("Is book == 'English'? I predict true.");
console.log(book == 'English', "\n");
